### ISSUE TITLE
Publish on Curseforge

### ISSUE THREAD

**Issue by SanderWxD** [avlad171/Ender-Quarry-Mod#2]
I love your mod and I would like to include it in my modpack.

Would you be willing and able to publish your mod on Curseforge so I can add it and redistribute it in my modpack?

Great work!

**Comment by avlad171** [comment]
Hello and thank you!

I stated it in project description and I say it again, this is not my mod. The code and assets belong to RWTema who coded ExtraUtilities. I merely ported his code because of the Ender Quarry not being in ExU2. I cannot publish something that is not mine (without author's consent, ofc).

As long as RWTema does not request this taken down feel free to use it for yourself, but Curseforge is a no go, sorry. I DM'd him 1 year ago, he still hasn't answered so this whole repository is in a grey area.

**Comment by SanderWxD** [comment]
Thank you for responding so quickly.

I understand but would you mind if I tried to apply it for approval of a [non-Curseforge mod](https://support.overwolf.com/en/support/solutions/articles/9000197913-non-curseforge-mods)?

For this, your project only needs to have a licence like the MIT or GPL license.

**Comment by avlad171** [comment]
How can I have a license on this if the code is not even mine? Best bet is to ask RWTema about this. I PM'd him 1 year ago on twitter and got no reply yet, so it might be worth to try.

My advice is to not post this anywere. I want to help people, not create trouble.
